apiVersion: v1
kind: ConfigMap
metadata:
  name: oro-config-override
  namespace: default
  annotations:
    meta.helm.sh/release-name: php-fpm-app
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  .env: |
    # Database configuration
    ORO_DB_DSN=postgresql://orodbuser:orodbpass@postgresql:5432/orodb?sslmode=disable
    # Redis configuration - CORRIGÉ
    ORO_REDIS_URL=redis://redis:6379
    ORO_REDIS_CACHE_DSN=redis://redis:6379/1
    ORO_REDIS_DOCTRINE_DSN=redis://redis:6379/2
    ORO_REDIS_LAYOUT_DSN=redis://redis:6379/3
    # Search Engine configuration
    ORO_SEARCH_ENGINE_DSN=orm://
    # Mailer configuration
    ORO_MAILER_DSN=native://default
    # Application settings
    ORO_SECRET=changeMe123SecretKeyForKubernetes2025
    ORO_ASSETS_VERSION=1
    # Environment
    APP_ENV=prod
    APP_DEBUG=false
  parameters.yml: |
    parameters:
        database_driver: pdo_pgsql
        database_host: postgresql
        database_port: 5432
        database_name: orodb
        database_user: orodbuser
        database_password: orodbpass
        database_server_version: '15.12'
        
        # Redis configuration - CORRIGÉ
        redis_dsn_cache: 'redis://redis:6379/1'
        redis_dsn_doctrine: 'redis://redis:6379/2'
        redis_dsn_layout: 'redis://redis:6379/3'
        redis_dsn_session: 'redis://redis:6379/0'
        
        # Search configuration
        search_engine_dsn: 'orm://'
        
        # App configuration
        secret: 'changeMe123SecretKeyForKubernetes2025'
        mailer_dsn: 'native://default'
        assets_version: ~
        assets_version_strategy: time_hash
        web_backend_prefix: '/admin'
        
        # Environment
        kernel.environment: prod
        kernel.debug: false
        
        # Websocket settings (désactivés pour simplifier)
        websocket_bind_address: '0.0.0.0'
        websocket_bind_port: 8080
        websocket_frontend_host: '*'
        websocket_frontend_port: 8080
        websocket_frontend_path: ''
        websocket_backend_host: '*'
        websocket_backend_port: 8080
        websocket_backend_path: ''
        websocket_backend_transport: tcp
        websocket_frontend_transport: ws